/*
 * fpn_neck.h
 * Feature Pyramid Network for HTDet FPGA (Vitis HLS)
 *
 * Config: in_channels=[64, 96, 128, 640], out_channels=256, num_outs=5
 *
 * Architecture (standard MMDetection FPN, top-down pathway):
 *
 *   C1 [64,  160, 160] → lateral_conv1 (1×1, 64→256)  ──────────────────────────── P2 [256, 160, 160]
 *   C2 [96,   80,  80] → lateral_conv2 (1×1, 96→256)  ← upsample(P3_pre) ─ add ─── P3 [256,  80,  80]
 *   C3 [128,  40,  40] → lateral_conv3 (1×1, 128→256) ← upsample(P4_pre) ─ add ─── P4 [256,  40,  40]
 *   C4 [640,  20,  20] → lateral_conv4 (1×1, 640→256) ← (top, no upsample) ─────── P5 [256,  20,  20]
 *   P5 ──── maxpool(2×2) ──────────────────────────────────────────────────────── P6 [256,  10,  10]
 *
 *   After add: each level gets a 3×3 output conv (256→256), no activation.
 *
 * Note: MMDetection FPN default is act_cfg=None — no activation on any conv.
 *
 * Weight layout (flat, from DDR) — [w, bias] only, no BN scale:
 *   lat1_w [256 *  64]  lat1_b [256]   (C1 lateral)
 *   lat2_w [256 *  96]  lat2_b [256]   (C2 lateral)
 *   lat3_w [256 * 128]  lat3_b [256]   (C3 lateral)
 *   lat4_w [256 * 640]  lat4_b [256]   (C4 lateral)
 *   out1_w [256*256*9]  out1_b [256]   (P2 output conv)
 *   out2_w [256*256*9]  out2_b [256]   (P3 output conv)
 *   out3_w [256*256*9]  out3_b [256]   (P4 output conv)
 *   out4_w [256*256*9]  out4_b [256]   (P5 output conv)
 *   (P6 is generated by stride-2 subsampling, no weights)
 *
 * Total FPN weight elements:
 *   Lateral: (64+96+128+640)*256 + 4*256 = 237,568 + 1,024 = 238,592
 *   Output:  4 * (256*256*9 + 256) = 4 * 590,080 = 2,360,320
 *   Total:   2,598,912
 */

#ifndef FPN_NECK_H
#define FPN_NECK_H

#include "fpga_types.h"
#include "fpga_utils.h"

// Definitions are in fpn_neck.cpp — add that file to the Vitis HLS project.

// 3×3 conv + bias, no activation (act_cfg=None).  in_ch = out_ch = FPN_OUT_CH = 256.
void fpn_conv3x3(
    const act_t*    input,
    act_t*          output,
    const weight_t* weights,
    const bias_t*   bias,
    int H, int W
);

// FPN forward pass: C1–C4 backbone features → P2–P6 pyramid outputs.
void fpn_neck(
    const act_t* c1,        // [C1_CH=64,  160, 160]
    const act_t* c2,        // [C2_CH=96,   80,  80]
    const act_t* c3,        // [C3_CH=128,  40,  40]
    const act_t* c4,        // [C4_CH=640,  20,  20]
    const weight_t* fpn_w,
    act_t* p2,              // [FPN_OUT_CH=256, 160, 160]
    act_t* p3,              // [FPN_OUT_CH=256,  80,  80]
    act_t* p4,              // [FPN_OUT_CH=256,  40,  40]
    act_t* p5,              // [FPN_OUT_CH=256,  20,  20]
    act_t* p6               // [FPN_OUT_CH=256,  10,  10]
);

#endif // FPN_NECK_H
