/*
 * fpn_neck.h
 * Feature Pyramid Network for HTDet FPGA (Vitis HLS)
 *
 * Config: in_channels=[64, 96, 128, 640], out_channels=256, num_outs=5
 *
 * Architecture (standard MMDetection FPN, top-down pathway):
 *
 *   C1 [64,  160, 160] → lateral_conv1 (1×1, 64→256)  ──────────────────────────── P2 [256, 160, 160]
 *   C2 [96,   80,  80] → lateral_conv2 (1×1, 96→256)  ← upsample(P3_pre) ─ add ─── P3 [256,  80,  80]
 *   C3 [128,  40,  40] → lateral_conv3 (1×1, 128→256) ← upsample(P4_pre) ─ add ─── P4 [256,  40,  40]
 *   C4 [640,  20,  20] → lateral_conv4 (1×1, 640→256) ← (top, no upsample) ─────── P5 [256,  20,  20]
 *   P5 ──── maxpool(2×2) ──────────────────────────────────────────────────────── P6 [256,  10,  10]
 *
 *   After add: each level gets a 3×3 output conv (256→256), no activation.
 *
 * Note: MMDetection FPN default is act_cfg=None — no activation on any conv.
 *
 * Weight layout (flat, from DDR) — [w, bias] only, no BN scale:
 *   lat1_w [256 *  64]  lat1_b [256]   (C1 lateral)
 *   lat2_w [256 *  96]  lat2_b [256]   (C2 lateral)
 *   lat3_w [256 * 128]  lat3_b [256]   (C3 lateral)
 *   lat4_w [256 * 640]  lat4_b [256]   (C4 lateral)
 *   out1_w [256*256*9]  out1_b [256]   (P2 output conv)
 *   out2_w [256*256*9]  out2_b [256]   (P3 output conv)
 *   out3_w [256*256*9]  out3_b [256]   (P4 output conv)
 *   out4_w [256*256*9]  out4_b [256]   (P5 output conv)
 *   (P6 is generated by stride-2 subsampling, no weights)
 *
 * Total FPN weight elements:
 *   Lateral: (64+96+128+640)*256 + 4*256 = 237,568 + 1,024 = 238,592
 *   Output:  4 * (256*256*9 + 256) = 4 * 590,080 = 2,360,320
 *   Total:   2,598,912
 */

#ifndef FPN_NECK_H
#define FPN_NECK_H

#include "fpga_types.h"
#include "fpga_utils.h"

// ============================================================
// 3×3 conv + bias, no activation (act_cfg=None in MMDetection FPN).
// Weight layout: [w, bias] — no BN scale.
// ============================================================
void fpn_conv3x3(
    const act_t*    input,
    act_t*          output,
    const weight_t* weights,
    const bias_t*   bias,
    int H, int W                    // both in_ch and out_ch = FPN_OUT_CH = 256
) {
    #pragma omp parallel for schedule(static)
    for (int oc = 0; oc < FPN_OUT_CH; oc++) {
        FPN3_OH: for (int oh = 0; oh < H; oh++) {
            FPN3_OW: for (int ow = 0; ow < W; ow++) {
                #pragma HLS PIPELINE II=1
                acc_t acc = 0;
                FPN3_IC: for (int ic = 0; ic < FPN_OUT_CH; ic++) {
                    FPN3_KH: for (int kh = 0; kh < 3; kh++) {
                        FPN3_KW: for (int kw = 0; kw < 3; kw++) {
                            int ih = oh + kh - 1;
                            int iw = ow + kw - 1;
                            if (ih >= 0 && ih < H && iw >= 0 && iw < W) {
                                acc += (acc_t)input[ic*H*W + ih*W + iw]
                                     * (acc_t)weights[(oc*FPN_OUT_CH+ic)*9 + kh*3+kw];
                            }
                        }
                    }
                }
                output[oc*H*W + oh*W + ow] = (act_t)(acc + (acc_t)bias[oc]);
            }
        }
    }
}

// ============================================================
// FPN FORWARD PASS
// ============================================================
void fpn_neck(
    // Backbone feature maps (on-chip BRAM inputs)
    const act_t* c1,    // [C1_CH=64,  P2_H=160, P2_W=160]
    const act_t* c2,    // [C2_CH=96,  P3_H=80,  P3_W=80]
    const act_t* c3,    // [C3_CH=128, P4_H=40,  P4_W=40]
    const act_t* c4,    // [C4_CH=640, P5_H=20,  P5_W=20]

    // FPN weights from DDR
    const weight_t* fpn_w,

    // Output FPN feature maps (on-chip)
    act_t* p2,   // [FPN_OUT_CH=256, 160, 160]
    act_t* p3,   // [FPN_OUT_CH=256,  80,  80]
    act_t* p4,   // [FPN_OUT_CH=256,  40,  40]
    act_t* p5,   // [FPN_OUT_CH=256,  20,  20]
    act_t* p6    // [FPN_OUT_CH=256,  10,  10]
) {
    // ---- Lateral connection buffers (after 1x1 conv) ----
    static act_t lat1[FPN_OUT_CH * P2_H * P2_W];   // 256*160*160 = 6.55M × 4B = 26.2MB → BRAM
    static act_t lat2[FPN_OUT_CH * P3_H * P3_W];   // 256*80*80  = 1.64M × 4B = 6.6MB
    static act_t lat3[FPN_OUT_CH * P4_H * P4_W];   // 256*40*40  = 409K  × 4B = 1.6MB
    static act_t lat4[FPN_OUT_CH * P5_H * P5_W];   // 256*20*20  = 102K  × 4B = 410KB
    #pragma HLS RESOURCE variable=lat1 core=RAM_T2P_BRAM
    #pragma HLS RESOURCE variable=lat2 core=RAM_T2P_BRAM
    #pragma HLS RESOURCE variable=lat3 core=RAM_T2P_BRAM
    #pragma HLS RESOURCE variable=lat4 core=RAM_T2P_BRAM

    // Upsample buffers (top-down pathway)
    static act_t up4[FPN_OUT_CH * P4_H * P4_W];   // 256*40*40  upsampled from P5
    static act_t up3[FPN_OUT_CH * P3_H * P3_W];   // 256*80*80  upsampled from P4
    static act_t up2[FPN_OUT_CH * P2_H * P2_W];   // 256*160*160 upsampled from P3
    #pragma HLS RESOURCE variable=up4 core=RAM_T2P_BRAM
    #pragma HLS RESOURCE variable=up3 core=RAM_T2P_BRAM
    #pragma HLS RESOURCE variable=up2 core=RAM_T2P_BRAM

    int off = 0;

    // ----------------------------------------------------------------
    // STEP 1: Lateral 1×1 convolutions (each Cx → 256)
    // ----------------------------------------------------------------

    // lat1 = conv1x1_plain(c1), in_ch=64  [w, bias] — no BN scale
    conv1x1_plain(c1, lat1, fpn_w+off, (const bias_t*)(fpn_w+off+FPN_OUT_CH*C1_CH),
                  C1_CH, FPN_OUT_CH, P2_H, P2_W);
    off += FPN_OUT_CH*C1_CH + FPN_OUT_CH;
    fake_quant_buf(lat1, FPN_OUT_CH*P2_H*P2_W, 0.04614f); // neck.lateral_convs.0

    // lat2 = conv1x1_plain(c2), in_ch=96
    conv1x1_plain(c2, lat2, fpn_w+off, (const bias_t*)(fpn_w+off+FPN_OUT_CH*C2_CH),
                  C2_CH, FPN_OUT_CH, P3_H, P3_W);
    off += FPN_OUT_CH*C2_CH + FPN_OUT_CH;
    fake_quant_buf(lat2, FPN_OUT_CH*P3_H*P3_W, 0.01437f); // neck.lateral_convs.1

    // lat3 = conv1x1_plain(c3), in_ch=128
    conv1x1_plain(c3, lat3, fpn_w+off, (const bias_t*)(fpn_w+off+FPN_OUT_CH*C3_CH),
                  C3_CH, FPN_OUT_CH, P4_H, P4_W);
    off += FPN_OUT_CH*C3_CH + FPN_OUT_CH;
    fake_quant_buf(lat3, FPN_OUT_CH*P4_H*P4_W, 0.01754f); // neck.lateral_convs.2

    // lat4 = conv1x1_plain(c4), in_ch=640
    conv1x1_plain(c4, lat4, fpn_w+off, (const bias_t*)(fpn_w+off+FPN_OUT_CH*C4_CH),
                  C4_CH, FPN_OUT_CH, P5_H, P5_W);
    off += FPN_OUT_CH*C4_CH + FPN_OUT_CH;
    fake_quant_buf(lat4, FPN_OUT_CH*P5_H*P5_W, 0.03082f); // neck.lateral_convs.3

    // ----------------------------------------------------------------
    // STEP 2: Top-down pathway (upsample + add)
    // P5_pre = lat4   (no upsample above P5)
    // P4_pre = lat3 + upsample(lat4)
    // P3_pre = lat2 + upsample(P4_pre)
    // P2_pre = lat1 + upsample(P3_pre)
    // ----------------------------------------------------------------

    // upsample lat4 (10×10 → 20×20), add to lat3
    upsample_2x(lat4, up4, FPN_OUT_CH, P5_H, P5_W);
    elem_add_inplace(lat3, up4, FPN_OUT_CH * P4_H * P4_W);

    // upsample lat3 (20×20 → 40×40), add to lat2
    upsample_2x(lat3, up3, FPN_OUT_CH, P4_H, P4_W);
    elem_add_inplace(lat2, up3, FPN_OUT_CH * P3_H * P3_W);

    // upsample lat2 (40×40 → 80×80), add to lat1
    upsample_2x(lat2, up2, FPN_OUT_CH, P3_H, P3_W);
    elem_add_inplace(lat1, up2, FPN_OUT_CH * P2_H * P2_W);

    // ----------------------------------------------------------------
    // STEP 3: Output 3×3 convolutions
    // ----------------------------------------------------------------

    // P2 = 3x3(lat1), no activation  [w, bias]
    fpn_conv3x3(lat1, p2, fpn_w+off, (const bias_t*)(fpn_w+off+FPN_OUT_CH*FPN_OUT_CH*9), P2_H, P2_W);
    off += FPN_OUT_CH*FPN_OUT_CH*9 + FPN_OUT_CH;
    fake_quant_buf(p2, FPN_OUT_CH*P2_H*P2_W, 0.05072f); // neck.fpn_convs.0

    // P3 = 3x3(lat2), no activation
    fpn_conv3x3(lat2, p3, fpn_w+off, (const bias_t*)(fpn_w+off+FPN_OUT_CH*FPN_OUT_CH*9), P3_H, P3_W);
    off += FPN_OUT_CH*FPN_OUT_CH*9 + FPN_OUT_CH;
    fake_quant_buf(p3, FPN_OUT_CH*P3_H*P3_W, 0.04035f); // neck.fpn_convs.1

    // P4 = 3x3(lat3), no activation
    fpn_conv3x3(lat3, p4, fpn_w+off, (const bias_t*)(fpn_w+off+FPN_OUT_CH*FPN_OUT_CH*9), P4_H, P4_W);
    off += FPN_OUT_CH*FPN_OUT_CH*9 + FPN_OUT_CH;
    fake_quant_buf(p4, FPN_OUT_CH*P4_H*P4_W, 0.02717f); // neck.fpn_convs.2

    // P5 = 3x3(lat4), no activation
    fpn_conv3x3(lat4, p5, fpn_w+off, (const bias_t*)(fpn_w+off+FPN_OUT_CH*FPN_OUT_CH*9), P5_H, P5_W);
    off += FPN_OUT_CH*FPN_OUT_CH*9 + FPN_OUT_CH;
    fake_quant_buf(p5, FPN_OUT_CH*P5_H*P5_W, 0.01892f); // neck.fpn_convs.3

    // P6 = maxpool2x2(P5)   (no learned weights)
    maxpool2x2(p5, p6, FPN_OUT_CH, P5_H, P5_W);
    fake_quant_buf(p6, FPN_OUT_CH*P6_H*P6_W, 0.01892f); // P6 reuses P5 scale (maxpool)
}

#endif // FPN_NECK_H
